#!/bin/bash

# Figure out paths automatically.
script_dir="$(dirname "$(realpath "$0")")"

if (( $? )); then
    echo 'Failed to determine script path!' 1>&2
    exit 1
fi

project_dir="$(dirname "$script_dir")"
guni_dir="$project_dir/guni"
sock_file="$guni_dir/site.sock"
pid_file="$guni_dir/site.pid"

stop_guni() {
    if [ -f "$pid_file" ]; then
        kill `cat -- "$pid_file"`
        rm -f -- "$pid_file"
    fi

    if [ -e "$sock_file" ]; then
        rm -f -- "$sock_file"
    fi
}

start_guni() {
    if [ ! -d "$guni_dir" ]; then
        mkdir -- "$guni_dir"
    fi

    if [ ! -d "$guni_dir" ]; then
        echo 'Failed to create gunicorn directory!' 1>&2
        exit 1
    fi

    source env/bin/activate

    python manage.py run_gunicorn -D -b "unix:$sock_file" -p "$pid_file"
}

case "$1" in
stop)
    stop_guni
;;
start)
    start_guni
;;
restart)
    stop_guni
    start_guni
;;
*)
    echo 'Please supply either stop, start, or restart' 2>&1
;;
esac

